version: "3"
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/opt/app