#!/bin/sh -e

# Replace ENV vars in configuration files
tmpfile=$(mktemp)
cat /usr/local/etc/php/conf.d/custom.ini | envsubst "$(env | cut -d= -f1 | sed -e 's/^/$/')" | tee "$tmpfile" > /dev/null
mv "$tmpfile" /usr/local/etc/php/conf.d/custom.ini


# pipe stderr to stdout and run php-fpm
exec 2>&1
php-fpm -y /usr/local/etc/php/php-fpm.conf -F -R